apiVersion: v1
kind: Service
metadata:
  name: prod-hello-service
  namespace: prod-hello
  labels:
    app: prod-hello
spec:
  type: NodePort
  selector:
    app: prod-hello
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: None
